<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Python报错：RuntimeError: The ‘data‘ object was created by an older version of PyG. - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Python报错：RuntimeError: The ‘data‘ object was created by an older version of PyG." />
<meta property="og:description" content="Python报错如下，非常长一大串：
JKNet_pyg.py:None (JKNet_pyg.py)
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\runner.py:341: in from_call
result: Optional[TResult] = func()
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\runner.py:372: in call = CallInfo.from_call(lambda: list(collector.collect()), “collect”)
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:531: in collect
self._inject_setup_module_fixture()
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:545: in _inject_setup_module_fixture
self.obj, (“setUpModule”, “setup_module”)
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:310: in obj
self._obj = obj = self._getobj()
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:528: in _getobj
return self._importtestmodule()
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:617: in importtestmodule
mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\pathlib.py:565: in import_path
importlib.import_module(module_name)
E:\anaconda\envs\pytorch_gpu\lib\importlib_init.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
但是，以下这句提醒我们了修改方式
RuntimeError: The &#39;data&#39; object was created by an older version of PyG." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/d9321d3148377a6c12a31468e7176e6d/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-08-08T10:37:32+08:00" />
<meta property="article:modified_time" content="2023-08-08T10:37:32+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Python报错：RuntimeError: The ‘data‘ object was created by an older version of PyG.</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="markdown_views prism-atom-one-dark">
                    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                        <path stroke-linecap="round" d="M5,0 0,2.5 5,5z" id="raphael-marker-block" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></path>
                    </svg>
                    <p>Python报错如下，非常长一大串：</p> 
<blockquote> 
 <p>JKNet_pyg.py:None (JKNet_pyg.py)<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\runner.py:341: in from_call<br> result: Optional[TResult] = func()<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\runner.py:372: in <br> call = CallInfo.from_call(lambda: list(collector.collect()), “collect”)<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:531: in collect<br> self._inject_setup_module_fixture()<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:545: in _inject_setup_module_fixture<br> self.obj, (“setUpModule”, “setup_module”)<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:310: in obj<br> self._obj = obj = self._getobj()<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:528: in _getobj<br> return self._importtestmodule()<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\python.py:617: in <em>importtestmodule<br> mod = import_path(self.path, mode=importmode, root=self.config.rootpath)<br> E:\anaconda\envs\pytorch_gpu\lib\site-packages_pytest\pathlib.py:565: in import_path<br> importlib.import_module(module_name)<br> E:\anaconda\envs\pytorch_gpu\lib\importlib_<em>init</em></em>.py:127: in import_module<br> return _bootstrap._gcd_import(name[level:], package, level)<br> </p> 
</blockquote> 
<p>但是，以下这句提醒我们了修改方式</p> 
<pre><code>RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.
</code></pre> 
<p>遇到的 <strong>RuntimeError</strong> 与 PyTorch Geometric（PyG）库的 data 对象和当前<strong>版本</strong>之间的兼容性有关。错误信息明确指出了需要做的事情：</p> 
<p><strong>‘data’ <strong>对象是由 PyG 的</strong>旧版本</strong>创建的。如果在加载已经存在的数据集时出现此错误，请删除数据集根文件夹中的 ‘processed/’ 目录，然后重试。</p> 
<p>这个错误可能是因为数据是用 PyG 的旧版本处理和保存的，而正在使用的当前版本无法处理那个旧格式。处理过的数据通常存储在数据集根文件夹内的 ‘processed/’ 目录中。</p> 
<p>以下是解决此错误的步骤：</p> 
<p><strong>找到 ‘processed/’ 目录</strong>：在你的数据集根文件夹中找到 ‘processed/’ 目录。这个文件夹将包含以二进制文件形式存储的预处理数据。</p> 
<p><strong>删除或重命名 ‘processed/’ 目录</strong>：你可以删除该目录或将其重命名（例如为 ‘processed_backup/’）以保留备份。</p> 
<p><strong>重新运行你的代码</strong>：一旦删除或重命名了 ‘processed/’ 目录，重新运行你的代码。PyG 将使用库的当前版本重新处理数据，这应该可以解决兼容性问题。</p> 
<p>按照这些步骤操作，错误应该可以解决。如果问题仍然存在，请确保运行代码与 PyG 的当前版本兼容，并考虑在必要时更新库。</p> 
<p>我直接把<strong>删除 ‘processed/’ 目录</strong>即可排除报错。</p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/63f1ea53bf55c9863e283805b56d5048/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Python报错：IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/a0506442be5476fc36db465d67b85e99/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">CentOS虚拟机 NAT模式连网</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>