<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>异常 Exception - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="异常 Exception" />
<meta property="og:description" content="一、异常定义： 导致程序的正常流程被中断的事件，叫做异常
FileNotFoundException 文件不存在异常
OutOfIndexException 数组下标越界异常
OutOfMemoryError 内存不足 ClassCastException 类型转换异常 ArithmaticException 除数为零 NullPointerException 空指针异常
二、异常处理常见手段： try catch finally throws
1. try catch
package exception; import java.io.File; import java.io.FileInputStream; import java.io.FileNotFoundException; public class TestException { public static void main(String[] args) { File f= new File(&#34;d:/LOL.exe&#34;); try{ System.out.println(&#34;试图打开 d:/LOL.exe&#34;); new FileInputStream(f); System.out.println(&#34;成功打开&#34;); } catch(FileNotFoundException e){ System.out.println(&#34;d:/LOL.exe不存在&#34;); e.printStackTrace(); } } } 2.使用异常的父类进行catch FileNotFoundException是Exception的子类，使用Exception也可以catch住FileNotFoundException
package exception; import java.io.File; import java.io.FileInputStream; import java.io.FileNotFoundException; public class TestException { public static void main(String[] args) { File f= new File(&#34;" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/2fcafb182ed18ef64668d80080189da5/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2018-02-07T01:52:16+08:00" />
<meta property="article:modified_time" content="2018-02-07T01:52:16+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">异常 Exception</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">一、异常定义： </span> 
<br style="font-size:15px; font-family:Helvetica; margin-bottom:3px; color:rgb(0,0,0)"> 
<p><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">导致程序的正常流程被中断的事件，叫做异常</span></p> 
<p><span style="font-family:Helvetica"><span style="color:#000000; background-color:rgb(255,255,255)"><span style="font-weight:bold"><span class="strong" style="font-family:Helvetica; padding-right:3px; padding-left:3px"><span style="font-size:14px"><span style="color:rgb(0,0,0); font-family:Helvetica; text-align:justify"><span class="strong" style="padding-right:3px; padding-left:3px"><span style="font-size:14px">FileNotFoundException</span></span><span style="font-size:12px"> </span></span>文件不存在异常</span></span></span></span><br> </span></p> 
<p><span style="background-color:rgb(255,255,255); color:rgb(0,0,0); font-family:Helvetica; font-size:15px">OutOfIndexException 数组下标越界异常</span></p> 
<p><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)"><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">OutOfMemoryError 内存不足</span><br style="font-size:15px; font-family:Helvetica; margin-bottom:3px; color:rgb(0,0,0); background-color:rgb(255,255,255)"> <span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">ClassCastException 类型转换异常</span><br style="font-size:15px; font-family:Helvetica; margin-bottom:3px; color:rgb(0,0,0); background-color:rgb(255,255,255)"> <span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">ArithmaticException 除数为零</span><br style="font-size:15px; font-family:Helvetica; margin-bottom:3px; color:rgb(0,0,0); background-color:rgb(255,255,255)"> <span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">NullPointerException 空指针异常</span><br> </span></p> 
<p><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)"><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">二、<span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)">异常处理常见手段： try catch finally throws</span></span></span></p> 
<p><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)"><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)"><span style="color:rgb(0,0,0); font-family:Helvetica; font-size:15px; background-color:rgb(255,255,255)"><span style="color:rgb(49,112,143); font-family:Helvetica; font-size:15px; background-color:rgb(217,237,247)"></span> 1.  try catch</span></span></span></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"></span></span></span></p> 
<pre><code class="language-html">package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
         
        File f= new File("d:/LOL.exe");
         
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
        catch(FileNotFoundException e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
         
    }
}</code></pre> 
<span style="font-size:12px"><strong>2.使用异常的父类进行catch</strong></span> 
<p></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><span style="color:rgb(49,112,143); font-family:Helvetica; background-color:rgb(217,237,247)"></span><strong>FileNotFoundException是Exception的子类，使用Exception也可以catch住FileNotFoundException</strong></span></span></span></span></p> 
<pre><code class="language-java">package exception;
  
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
  
public class TestException {
  
    public static void main(String[] args) {
          
        File f= new File("d:/LOL.exe");
          
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
         
        catch(Exception e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
          
    }
}</code></pre>3 : 多异常捕捉办法1 
<p></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><strong>有的时候一段代码会抛出多种异常，比如<br>  <br> new FileInputStream(f);<br> Date d = sdf.parse("2016-06-03");</strong></span></span></span></span></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><strong><br> 这段代码，会抛出 文件不存在异常 FileNotFoundException 和 解析异常ParseException <br> 解决办法之一是分别进行catch<br>  <br> catch (FileNotFoundException e) {<!-- --><br>     System.out.println("d:/LOL.exe不存在");<br>     e.printStackTrace();<br> } catch (ParseException e) {<!-- --><br>     System.out.println("日期格式解析错误");<br>     e.printStackTrace();<br> }</strong></span></span></span></span></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><strong></strong></span></span></span></span></p> 
<pre><code class="language-java">package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
 
public class TestException {
 
    public static void main(String[] args) {
 
        File f = new File("d:/LOL.exe");
 
        try {
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse("2016-06-03");
        } catch (FileNotFoundException e) {
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        } catch (ParseException e) {
            System.out.println("日期格式解析错误");
            e.printStackTrace();
        }
    }
}</code></pre>4 . 多异常捕捉办法2 
<br> 另一个种办法是把多个异常，放在一个catch里统一捕捉  
<br> catch (FileNotFoundException | ParseException e) { 
<br> 这种方式从 JDK7开始支持，好处是捕捉的代码更紧凑，不足之处是，一旦发生异常，不能确定到底是哪种异常，需要通过instanceof 进行判断具体的异常类型 
<br>   
<br> if (e instanceof FileNotFoundException) 
<br> 
<span style="white-space:pre"></span>System.out.println("d:/LOL.exe不存在"); 
<br> if (e instanceof ParseException) 
<br> 
<span style="white-space:pre"></span>System.out.println("日期格式解析错误"); 
<br> 
<p></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><strong></strong></span></span></span></span></p> 
<pre><code class="language-java">package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
 
public class TestException {
 
    public static void main(String[] args) {
 
        File f = new File("d:/LOL.exe");
 
        try {
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse("2016-06-03");
        } catch (FileNotFoundException | ParseException e) {
            if (e instanceof FileNotFoundException)
                System.out.println("d:/LOL.exe不存在");
            if (e instanceof ParseException)
                System.out.println("日期格式解析错误");
 
            e.printStackTrace();
        }
 
    }
}</code></pre> 5 . finally 
<p></p> 
<p><span style="font-size:12px; background-color:rgb(255,255,255); font-family:Helvetica">无论是否出现异常，finally中的代码都会被执行</span></p> 
<p><span style="font-size:12px; background-color:rgb(255,255,255); font-family:Helvetica"></span></p> 
<pre><code class="language-java">package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
         
        File f= new File("d:/LOL.exe");
         
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
        catch(FileNotFoundException e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
        finally{
            System.out.println("无论文件是否存在， 都会执行的代码");
        }
    }
}</code></pre> 6 . throws 
<br> 考虑如下情况： 
<br>     主方法调用method1 
<br>     method1调用method2 
<br>     method2中打开文件 
<p></p> 
<p><span style="font-size:12px; background-color:rgb(255,255,255); font-family:Helvetica">method2中需要进行异常处理<br> 但是method2不打算处理，而是把这个异常通过throws抛出去<br> 那么method1就会接到该异常。 处理办法也是两种，要么是try catch处理掉，要么也是抛出去。<br> method1选择本地try catch住 一旦try catch住了，就相当于把这个异常消化掉了，主方法在调用method1的时候，就不需要进行异常处理了<br> </span></p> 
<p><span style="font-size:12px; background-color:rgb(255,255,255); font-family:Helvetica"></span></p> 
<pre><code class="language-java">package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
        method1();
 
    }
 
    private static void method1() {
        try {
            method2();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
 
    }
 
    private static void method2() throws FileNotFoundException {
 
        File f = new File("d:/LOL.exe");
 
        System.out.println("试图打开 d:/LOL.exe");
        new FileInputStream(f);
        System.out.println("成功打开");
 
    }
}</code></pre> 7 : throw和throws的区别  
<br> throws与throw这两个关键字接近，不过意义不一样，有如下区别： 
<br> 1. throws 出现在方法声明上，而throw通常都出现在方法体内。 
<br> 2. throws 表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某个异常对象。 
<p></p> http://how2j.cn/k/exception/exception-trycatch/336.html# 
<br> 
<p><span style="font-size:12px; background-color:rgb(255,255,255); font-family:Helvetica"><br> <br> </span></p> 
<p><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-family:Helvetica; background-color:rgb(255,255,255)"><span style="font-size:12px"><strong><br> </strong></span></span></span></span></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/e900ea599315f49d7a8b88586d62fd82/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">基于Memcached分布式系统DRDoS拒绝服务攻击技术研究</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/22d28d33d8ed8fcebf08aeff879772b2/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">&amp;times变成x</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>