<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>try-catch处理异常 - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="try-catch处理异常" />
<meta property="og:description" content="目录
1. try-catch处理异常
2. finally
3. throw 和 throws
3. 自定义异常
4. 总结
6. 内部类
1. try-catch处理异常 使用 try-catch 处理异常
try：表示将有可能出现异常的代码书写在 try 代码块中
catch：用于捕获 try 代码块中有可能出现的异常
try不能单独使用必须结合 catch 或者 finally 或者 catch-finally
catch不能单独使用 必须结合try
情况1：出现异常 并且能够被捕获到
public class TestTryCatch1 { public static void main(String[] args) { try{ Scanner in = new Scanner(System.in); System.out.print(&#34;请输入被除数:&#34;); int num1 = in.nextInt(); System.out.print(&#34;请输入除数:&#34;); int num2 = in.nextInt(); System.out.println(num1&#43;&#34;/&#34;&#43; num2 &#43;&#34;=&#34;&#43; num1/ num2); } catch(InputMismatchException exception){ exception." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/bbdcb7792512d185ae1002f82eb069c8/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-04-17T20:19:08+08:00" />
<meta property="article:modified_time" content="2023-04-17T20:19:08+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">try-catch处理异常</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p id="main-toc"><strong>目录</strong></p> 
<p id="-toc" style="margin-left:40px;"></p> 
<p id="1.%20try-catch%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8-toc" style="margin-left:40px;"><a href="#1.%20try-catch%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8" rel="nofollow">1. try-catch处理异常</a></p> 
<p id="2.%20finally-toc" style="margin-left:40px;"><a href="#2.%20finally" rel="nofollow">2. finally</a></p> 
<p id="3.%20throw%20%E5%92%8C%20throws-toc" style="margin-left:40px;"><a href="#3.%20throw%20%E5%92%8C%20throws" rel="nofollow">3. throw 和 throws</a></p> 
<p id="3.%20%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8-toc" style="margin-left:40px;"><a href="#3.%20%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8" rel="nofollow">3. 自定义异常</a></p> 
<p id="4.%20%E6%80%BB%E7%BB%93-toc" style="margin-left:40px;"><a href="#4.%20%E6%80%BB%E7%BB%93" rel="nofollow">4. 总结</a></p> 
<p id="6.%20%E5%86%85%E9%83%A8%E7%B1%BB-toc" style="margin-left:80px;"><a href="#6.%20%E5%86%85%E9%83%A8%E7%B1%BB" rel="nofollow">6. 内部类</a></p> 
<hr id="hr-toc"> 
<p></p> 
<h3 id="1.%20try-catch%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8">1. try-catch处理异常</h3> 
<blockquote> 
 <p>使用 try-catch 处理异常</p> 
 <p>try：表示将有<span style="color:#fe2c24;">可能出现异常的代码</span>书写在 try 代码块中</p> 
 <p>catch：用于捕获 try 代码块中有可能出现的异常</p> 
 <p>try不能单独使用必须结合 catch 或者 finally 或者 catch-finally</p> 
 <p>catch不能单独使用  必须结合try</p> 
</blockquote> 
<blockquote> 
 <p>情况1：出现异常 并且能够被捕获到</p> 
</blockquote> 
<pre><code class="language-java">public class TestTryCatch1 {
    public static void main(String[] args) {
        try{
            Scanner in = new Scanner(System.in);
            System.out.print("请输入被除数:");
            int num1 = in.nextInt();
            System.out.print("请输入除数:");
            int num2 = in.nextInt();
            System.out.println(num1+"/"+ num2 +"="+ num1/ num2);
        } catch(InputMismatchException exception){
            exception.printStackTrace(); // 打印异常堆栈信息 具体为 哪个类 哪一行 什么原因出错了
        }

        System.out.println("感谢使用本程序！");
    }
}</code></pre> 
<blockquote> 
 <p>情况2：出现异常  但是捕获的异常和出现的异常类型不匹配依然会中断程序</p> 
</blockquote> 
<pre><code class="language-java">public class TestTryCatch2 {
    public static void main(String[] args) {
        try{
            Scanner in = new Scanner(System.in);
            System.out.print("请输入被除数:");
            int num1 = in.nextInt();
            System.out.print("请输入除数:");
            int num2 = in.nextInt();
            System.out.println(num1+"/"+ num2 +"="+ num1/ num2);
        } catch(InputMismatchException exception){
            exception.printStackTrace(); // 打印异常堆栈信息 具体为 哪个类 哪一行 什么原因出错了
        }
        System.out.println("感谢使用本程序！");
    }
}</code></pre> 
<blockquote> 
 <p>情况3：处理多种异常</p> 
 <p>可以书写多个catch块，注意：写多个catch处理异常 先写子类后写父类，否则编译报错</p> 
 <p>也可以使用 | 或运算符 分割 书写多个异常</p> 
</blockquote> 
<pre><code class="language-java">public class TestTryCatch3 {
    public static void main(String[] args) {
        try{
            Scanner in = new Scanner(System.in);
            System.out.print("请输入被除数:");
            int num1 = in.nextInt();
            System.out.print("请输入除数:");
            int num2 = in.nextInt();
            System.out.println(num1+"/"+ num2 +"="+ num1/ num2);
        } catch(InputMismatchException  | ArithmeticException | NullPointerException exception){
            exception.printStackTrace(); // 打印异常堆栈信息 具体为 哪个类 哪一行 什么原因出错了
        }

        System.out.println("感谢使用本程序！");
    }
}</code></pre> 
<h3 id="2.%20finally">2. finally</h3> 
<blockquote> 
 <p>finally：表示最终都会执行的代码，书写在 finally 代码块中</p> 
 <p>finally不能单独使用  必须结合 try 或者 try-catch</p> 
 <p>不执行finally 的唯一情况：在执行finally之前退出JVM虚拟机</p> 
 <p>System.exit(int status):表示退出JVM虚拟机  0表示正常退出，非0表示不正常退出</p> 
</blockquote> 
<pre><code class="language-java">public class TestFinally1 {
    public static void main(String[] args) {
        try{
            Scanner in = new Scanner(System.in);
            System.out.print("请输入被除数:");
            int num1 = in.nextInt();
            System.out.print("请输入除数:");
            int num2 = in.nextInt();
            System.out.println(num1+"/"+ num2 +"="+ num1/ num2);

//            System.exit(12345);

        } catch(InputMismatchException e){
            e.printStackTrace();
        } finally{
            System.out.println("感谢使用本程序！");
        }
    }
}</code></pre> 
<blockquote> 
 <p>值传递和引用传递：</p> 
 <p>finally面试题：</p> 
 <p>在 try 中return值，如果为基本数据类型，则在finally中对返回值的修改  不会改变原返回值</p> 
 <p>在 try 中return值，如果为引用数据类型，则在finally中对返回值的修改，会改变原返回值，比如数组类型</p> 
</blockquote> 
<pre><code class="language-java">public class TestFinally2 {

    public static int getNum(){
        int num = 10;
        try{
            num++;
            return num;
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            num++;
        }
        return num;
    }
    public static int[] getNums(){
        int [] nums = {1,2,3,4,5};
        try{
            return nums;
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            for(int i =0;i&lt; nums.length;i++){
                nums[i]++;
            }
        }
        return nums;
    }
    public static void main(String[] args) {
        System.out.println(getNum()); // 11

        int[] nums = getNums();

        System.out.println(Arrays.toString(nums));
    }
}</code></pre> 
<h3 id="3.%20throw%20%E5%92%8C%20throws">3. throw 和 throws</h3> 
<blockquote> 
 <p>RuntimeException  运行时异常：RuntimeException 及其子类属于运行时异常，即程序运行期间出现异常</p> 
 <p>CheckedException 检查异常（受检异常）：除运行时异常外，其余异常都属于检查异常</p> 
 <p> </p> 
 <p>throw：</p> 
 <p>用于方法体内抛出异常，书写在方法体内，一句话只能抛出一个异常</p> 
 <p>        针对抛出的异常类型不同 决定书是否需要立即处理</p> 
 <p>        如果抛出的是运行时异常  则不必处理</p> 
 <p>        如果抛出的是检查异常  则必须处理  使用try-catch处理，或者用 throws 声明</p> 
 <p>throws：</p> 
 <p>用于定义方法的时候声明当前方法出现了哪些异常</p> 
 <p>        </p> 
 <p>针对声明的异常 根据不同的类型有两种处理方案：</p> 
 <p>        1.如果声明的运行时异常 则不必处理</p> 
 <p>        2.如果声明的是检查异常 则必须处理 使用try-catch处理 或者 继续声明给JVM虚拟机</p> 
</blockquote> 
<p style="text-align:center;"><img alt="" src="https://images2.imgbox.com/f8/b9/5HNBhFIm_o.png"></p> 
<p> </p> 
<pre><code class="language-java">public class TestThrows {
    public static void m1() {
        throw new ArithmeticException("除数不能为0");
    }

    public static void m2(){
        throw new RuntimeException();
    }

    public static void m3() throws NullPointerException{
        throw new NullPointerException();
    }

    public static void m4() throws ClassNotFoundException,IOException, SQLException {
        throw new ClassNotFoundException();
    }

    public static void m5() throws IOException {
        throw new IOException();
    }

    public static void m6(){
        try {
            throw new IllegalAccessException();
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
    public static void main(String[] args) throws IOException {
        m1();
        m2();
        m3();

        try {
            m4();
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException(e);
        }
        m5();

        m6();
    }
}</code></pre> 
<h3 id="3.%20%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8">3. 自定义异常</h3> 
<blockquote> 
 <p>实际开发中，JDK提供异常不能满足我们的开发需求时，需要自定义异常</p> 
 <p>步骤：</p> 
 <p>1.继承Exception 或者 RuntimeException 二者其中之一</p> 
 <p>2.编写构造方法 调用父类的构造实现异常信息初始化</p> 
</blockquote> 
<pre><code class="language-java">public class Student {
    private String name;
    private int age;

    private int score;



    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) throws InputAgeOutOfBoundsException {
        if(age &gt;= 0 &amp;&amp; age &lt;= 130){
            this.age = age;
        }else{
            throw new InputAgeOutOfBoundsException("年龄不合法" + age);
        }

    }
    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        if(score &gt;= 0 &amp;&amp; score &lt;= 100 ){
            this.score = score;
        }else{
            throw new InputScoreException("分数不合法" + score);
        }

    }

    public static void main(String[] args) throws InputAgeOutOfBoundsException {
        Student stu1 = new Student();

        stu1.setAge(999);

        stu1.setScore(888);

    }
}</code></pre> 
<pre><code class="language-java">public class InputAgeOutOfBoundsException extends Exception{
    public InputAgeOutOfBoundsException(String message){
        super(message);
    }

}
</code></pre> 
<pre><code class="language-java">public class InputScoreException extends RuntimeException{
    public InputScoreException(String message){
        super(message);
    }
}</code></pre> 
<h3 id="4.%20%E6%80%BB%E7%BB%93">4. 总结</h3> 
<blockquote> 
 <p>异常处理与性能</p> 
 <p>异常只能用于非正常情况</p> 
 <p>不要将过于庞大的代码块放在try中</p> 
 <p>在catch中指定具体的异常类型</p> 
 <p>需要对捕获的异常做处理</p> 
</blockquote> 
<h4 id="6.%20%E5%86%85%E9%83%A8%E7%B1%BB">6. 内部类</h4> 
<p>内部类：即一个类中 再书写其他的类</p> 
<p>普通内部类</p> 
<p>静态内部类</p> 
<p>局部内部类</p> 
<p>匿名内部类</p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/83fd2d86f113ac6132ee82529d25dd79/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Faster RCNN详解（个人理解）</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/663e4c648a307621f43b52fd1454ad39/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">Zdal 配置的几种方式（SOFABoot）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>