<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>js中try-catch的理解 - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="js中try-catch的理解" />
<meta property="og:description" content="最近在MatLab中看到了try-catch语句的应用，正好今天看到了js中的try-catch语句，就来简单的总结一下吧。
try-catch 语句：作用捕获异常语句
执行流程：先执行try中的语句，如果有错误，就会将错误抛出，并且被catch捕获并去执行，这时候就会执行catch里的语句，而且不论try中有没有抛出和错误，finally语句都会去执行其中自己的代码块
&lt;!DOCTYPE html&gt; &lt;html lang=&#34;en&#34;&gt; &lt;head&gt; &lt;meta charset=&#34;UTF-8&#34;&gt; &lt;title&gt;Document&lt;/title&gt; &lt;/head&gt; &lt;body&gt; &lt;script&gt; try{ console.log(a); }catch{ console.log(1); } &lt;/script&gt; &lt;/body&gt; &lt;/html&gt; 因为try中有错误，就会去执行catch中的代码块
执行结果：
try中代码的执行也是顺序的，直到遇到错误位置
在catch语句中遇到错误仍然是会报错的
无论是在try中有没有错误，finally中的代码块都会被执行，并且，如果catch和finally中都存在错误的话，只报错finally中的错误
最后再举一个例子吧
&lt;!DOCTYPE html&gt; &lt;html lang=&#34;en&#34;&gt; &lt;head&gt; &lt;meta charset=&#34;UTF-8&#34;&gt; &lt;title&gt;Document&lt;/title&gt; &lt;/head&gt; &lt;body&gt; &lt;script&gt; (function() { try{ var a = 1; console.log(a); //打印a throw Error(a); //抛出错误a }catch (a){ console.log(&#34;捕获到了错误a:&#34;&#43;a); console.log(b); //此时b未定义，没有finally的话就会报错 }finally{ console.log(&#34;finally执行&#34;); console.log(c); //此时c未定义,会报错； } })(); &lt;/script&gt; &lt;/body&gt; &lt;/html&gt; 结果：" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/4946e2be3fdf1b94c72b68940f946059/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2018-10-23T15:13:08+08:00" />
<meta property="article:modified_time" content="2018-10-23T15:13:08+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">js中try-catch的理解</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>最近在MatLab中看到了try-catch语句的应用，正好今天看到了js中的try-catch语句，就来简单的总结一下吧。</p> 
<p>try-catch 语句：作用捕获异常语句</p> 
<p>执行流程：先执行try中的语句，如果有错误，就会将错误抛出，并且被catch捕获并去执行，这时候就会执行catch里的语句，而且不论try中有没有抛出和错误，finally语句都会去执行其中自己的代码块</p> 
<pre class="has"><code>&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
	&lt;meta charset="UTF-8"&gt;
	&lt;title&gt;Document&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;script&gt;
	 try{
	 	console.log(a);
	 }catch{
	 	console.log(1);
	 }
	&lt;/script&gt;
	
&lt;/body&gt;
&lt;/html&gt;</code></pre> 
<p>因为try中有错误，就会去执行catch中的代码块</p> 
<p>执行结果：</p> 
<p><img alt="" class="has" height="204" src="https://images2.imgbox.com/f7/93/lnofgeNz_o.png" width="342"></p> 
<p>try中代码的执行也是顺序的，直到遇到错误位置</p> 
<p>在catch语句中遇到错误仍然是会报错的</p> 
<p>无论是在try中有没有错误，finally中的代码块都会被执行，并且，如果catch和finally中都存在错误的话，只报错finally中的错误</p> 
<p>最后再举一个例子吧</p> 
<pre class="has"><code>&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
	&lt;meta charset="UTF-8"&gt;
	&lt;title&gt;Document&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;script&gt;
	(function() {
		try{
			var a = 1;
			console.log(a);  //打印a
			throw Error(a);  //抛出错误a
		}catch (a){
			console.log("捕获到了错误a:"+a);
			console.log(b);  //此时b未定义，没有finally的话就会报错
		}finally{
			console.log("finally执行");
			console.log(c);  //此时c未定义,会报错；
		}
	})();
	&lt;/script&gt;
	
&lt;/body&gt;
&lt;/html&gt;</code></pre> 
<p>结果：</p> 
<p><img alt="" class="has" height="345" src="https://images2.imgbox.com/7a/68/Dyts2SpB_o.png" width="1200"></p> 
<p> </p> 
<p> </p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/afd6917bce7865b4de9981eaeac97d4d/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">使用shell脚本对比两个文件内容差异</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/f56a35a6dc4960004b1577eb6a486c52/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">python知识点：tkinter-filedialog-asksaveasfilename参数</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>